name: split_ease
description: "Split expenses easily with friends and roommates."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.11.2
  build_runner: ^2.15.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#1A1A1A"
  image: "assets/icon/app_icon.png"
  android_12:
    color: "#1A1A1A"
    image: "assets/icon/app_icon.png"  