// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:split_ease/models/expense.dart';
import 'package:split_ease/models/group.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseAdapter());
    registerAdapter(GroupAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseAdapter());
    registerAdapter(GroupAdapter());
  }
}
